name: Create Releases

on: [push]

jobs:
  build:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - 16
        os:
          - linux
          - macos
          - win
    steps:
      - uses: actions/checkout@v3
      - name: Install node ${{ matrix.node-version }}
      - uses: actions/setup-node@v3
        if: success()
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        if: success()
        run: npm ci
      - name: Build
        if: success()
        run: npm run build:server -- --minify
      - name: Package into node binary
        if: success()
        uses: lando/pkg-action@v2
        with:
          entrypoint: backend/out/sub-store
          arch: ${{ matrix.arch }}
          node-version: node${{ matrix.node-version }}
          os: ${{ matrix.os }}